modLoader = "kotlinforforge"
loaderVersion = "[3.12,)"
license = "${license}"
issueTrackerURL = "https://github.com/Erdragh/AstralBot/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${title}"
displayURL = "https://modrinth.com/mod/astralbot"
logoFile = "icon.png"
authors = "${credits}"
description = "${description}"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.18.3)"
ordering = "NONE"
side = "BOTH"