modLoader = "kotlinforforge"
loaderVersion = "${kff_loader_range}"
license = "${license}"
issueTrackerURL = "https://github.com/Erdragh/AstralBot/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://modrinth.com/mod/astralbot"
logoFile = "icon.png"
authors = "${mod_author}"
description = "${description}"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "forgeconfigapiport"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"