kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G -XX:ThreadStackSize=4096 -XX:CompilerThreadStackSize=4096

# Minecraft things
enabledPlatforms=fabric,neoforge

version=1.5.4
group=dev.erdragh.astralbot
modName=AstralBot
modId=astralbot
modAuthor=Erdragh

license=MIT
description=Discord Bot and Minecraft Mod in one bundle.
credits=Erdragh