[versions]
java = "21"
kotlin = "2.1.10"
moddev = "2.0.78"
loom = "1.9-SNAPSHOT"
dokka = "2.0.0"

kotlinx-coroutines = "1.10.1"

minecraft = "1.21.1"
minecraftRange = "[1.21.1, 1.21.2)"

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment = "2024.11.17"
parchmentMC = "1.21.1"

neoforge = "21.1.116"
neoforgeRange = "[21.1, 21.2)"
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neoForm = "1.21.1-20240808.144430"
kff = "5.7.0"
kffRange = "[5.7, )"

slf4j = "2.0.9"

fcapi = "21.1.3"

fabricLoader = "0.16.10"
fabricApi = "0.102.0+1.21.1"
flk = "1.13.1+kotlin.2.1.10"
publish = "0.8.4"

sqlite = "3.49.0.0"
commonmark = "0.24.0"

mixin = "0.8.5"
mixinExtras = "0.3.5"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
fabricApi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabricApi" }
flk = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "flk" }
kff = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "kff" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixinExtras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinExtras" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }
commonmark = { group = "org.commonmark", name = "commonmark", version.ref = "commonmark" }
fcapi-fabric = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-fabric", version.ref = "fcapi" }
fcapi-common = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-common-neoforgeapi", version.ref = "fcapi" }
parchment = { group = "org.parchmentmc.data", name = "parchment-1.21.1", version.ref = "parchment" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
loom = { id = "fabric-loom", version.ref = "loom" }
publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "publish" }