modLoader = "kotlinforforge"
loaderVersion = "[4.10,)"
license = "MIT License"
issueTrackerURL = "https://github.com/Erdragh/AstralBot/issues"

[[mixins]]
config = "astralbot-common.mixins.json"
[[mixins]]
config = "astralbot.mixins.json"

[[mods]]
modId = "astralbot"
version = "${version}"
displayName = "AstralBot"
displayURL = "https://modrinth.com/mod/astralbot"
logoFile = "icon.png"
authors = "Erdragh"
description = "Discord Bot and Minecraft Mod in one bundle."

[[dependencies.astralbot]]
modId = "neoforge"
type = "required"
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.astralbot]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"