plugins {
    id("groovy-gradle-plugin")
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:${libs.versions.kotlin.get()}")
    implementation("org.jetbrains.dokka:dokka-gradle-plugin:${libs.versions.dokka.get()}")
    implementation("me.modmuss50:mod-publish-plugin:${libs.versions.publish.get()}")
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

